spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            admin:
              - uri: http://localhost:${server.port}
                metadata:
                  management.context-path: ${management.endpoints.web.base-path}
            application:
              - uri: http://${monitored.application.host}:${monitored.application.port}
                metadata:
                  management.context-path: ${monitored.application.actuator-endpoint}

monitored:
  application:
    host: 127.0.0.1
    port: 8080
    actuator-endpoint: /admin