spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
        service-labels:
          tech-stack: springboot
        include-not-ready-addresses: true
  main:
    cloud-platform: kubernetes