server:
  servlet:
    jsp:
      registered: false
  shutdown: graceful
  port: 8081

spring:
  boot:
    admin:
      monitor:
        info-interval: 10s
        status-interval: 5000ms
      discovery:
        converter:
          management-context-path: /admin
  security:
    user:
      name:
      password:
      roles: ADMIN
  application:
    name: boot-admin
    admin:
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  jmx:
    enabled: false
  main:
    cloud-platform: none

management:
  endpoint:
    env:
      post:
        enabled: true
      show-values: when_authorized
    shutdown:
      enabled: true
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    configprops:
      show-values: when_authorized
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: '*'
  info:
    java:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
    os:
      enabled: true

actuator:
  username:
  password: